variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
  - package
  - deploy


build_job:
  stage: build
  tags:
    - docker
  script:
    - echo "Maven compile started"
    - "mvn compile"

test_job:
  stage: test
  tags:
    - docker
  script:
    - echo "Maven test started"
    - "mvn test"

package_job:
  stage: package
  tags:
    - docker
  script:
    - echo "Maven packaging started"
    - "mvn package"

deploy_job:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Maven deploy started"
