default:
  cache: # 全局缓存配置
    paths:
      - .m2/repository
      - target/

stages:
  - build

package:
  stage: build
  image: maven:3.9.8-eclipse-temurin-21
  script:
    - mvn test --ntp -B -U clean package
  artifacts:
    when: always
    paths:
      - target/*.jar
