variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3.9.8-eclipse-temurin-21

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - deploy
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Maven packaging  started"
    - "mvn -ntp -B -U package"

deploy_image:
  stage: deploy
  image: docker:latest
  tags:
    - docker
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_USERNAME/$CI_PROJECT_NAME:latest .
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:latest

deploy_jar:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Maven deploy started"
    - "mvn -ntp -B -U deploy"
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  tags:
    - docker
  script:
    - docker pull $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
    - docker run $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
