variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - deploy
  - test

build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-21
  tags:
    - docker
  script:
    - echo "Maven packaging  started"
    - "mvn -ntp -B -U package"

deploy_jar:
  stage: deploy
  image: maven:3.9.8-eclipse-temurin-21
  tags:
    - docker
  script:
    - echo "Maven deploy started"
    - "mvn -ntp -B -U deploy"
  artifacts:
    paths:
      - target/*.jar

deploy_image:
  stage: deploy
  #  rules:
  #    - if: '$CI_COMMIT_TAG'
  tags:
    - docker
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_USERNAME/$CI_PROJECT_NAME:latest -t $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA -f Dockerfile.simple .
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA

test:
  stage: test
  tags:
    - docker
  script:
    - docker pull $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
    - docker run $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
