build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-21
  cache:
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/*.jar 
  script:
    - mvn package --ntp -DskipTests -B
