build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-21
  cache:
    paths:
      - .m2/repository
      - target/
  script:
    - mvn package --ntp -DskipTests -B
  artifacts:
    when: always
    paths:
      - target/*.jar 