variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3-jdk-8

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Maven compile started"
    - "mvn -ntp -B -U compile"

test:
  stage: test
  tags:
    - docker
  script:
    - echo "Maven test started"
    - "mvn -ntp -B -U test"

package:
  stage: package
  tags:
    - docker
  script:
    - echo "Maven packaging started"
    - "mvn -ntp -B -U package -DskipTests"

deploy_image:
  stage: deploy
  image: docker
  tags:
    - docker
  script:
    - echo "Maven deploy started"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USERNAME/$CI_PROJECT_NAME:latest .
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:latest

deploy_jar:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Maven deploy started"
    - "mvn -ntp -B -U deploy"
  artifacts:
    paths:
      - target/*.jar
