services:
  mysql:
    image: bitnami/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=spring-boot3-monolith
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/bitnami/mysql/data

  redis:
    restart: always
    image: bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli","--raw", "incr","ping" ]
      interval: 2s
      retries: 30

  postgres:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=spring-boot3-monolith
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  sonarqube:
    image: sonarqube:10.6-community
    ports:
      - "9000:9000"
    #        environment:
    #            # CREATE USER sonar WITH PASSWORD 'sonar';
    #            # CREATE DATABASE sonar owner sonar;
    #            # GRANT ALL ON SCHEMA public TO sonar;
    #            - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
    #            - SONAR_JDBC_USERNAME=sonar
    #            - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonar_data:/opt/sonarqube

  artifactory-oss:
    image: releases-docker.jfrog.io/jfrog/artifactory-jcr:7.84.15
    environment:
      - JF_SHARED_DATABASE_TYPE=postgresql
      # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
      - JF_SHARED_DATABASE_USERNAME=artifactory
      - JF_SHARED_DATABASE_PASSWORD=password
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://postgresql:5432/artifactory
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro

  nexus:
    image: sonatype/nexus3
    platform: linux/amd64
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
      - /etc/localtime:/etc/localtime:ro

  selenium:
    # selenium 需要 chrome 浏览器和 chromeDriver 版本一致
    image: selenium/standalone-chrome:4.22.0-20240621
    platform: linux/amd64
    ports:
      - "4444:4444"

  yapi:
    image: jayfong/yapi:latest
    platform: linux/amd64
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@docker.yapi
      - YAPI_ADMIN_PASSWORD=adm1n
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  jenkins:
    image: jenkins/jenkins:jdk21
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

  gitlab:
    image: gitlab/gitlab-ce
    platform: linux/amd64
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8880"
        nginx['enable'] = false
    ports:
      - '8880:8880'
      - '2222:22'
    volumes:
      - gitlab_data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  # https://elnatantorres.medium.com/configuring-rabbitmq-on-its-startup-with-docker-d219af4b751a
  rabbitmq:
    image: bitnami/rabbitmq:3.13.3
    environment:
      RABBITMQ_LOAD_DEFINITIONS: "true"
      # definition is set with -> user: password
      RABBITMQ_DEFINITIONS_FILE: /etc/rabbitmq/definitions.json
      RABBITMQ_PLUGINS: rabbitmq_shovel rabbitmq_shovel_management rabbitmq_delayed_message_exchange
      RABBITMQ_COMMUNITY_PLUGINS: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./scripts/configs/rabbitmq-definition.json:/etc/rabbitmq/definitions.json
      - ./scripts/configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_data:/bitnami/rabbitmq/mnesia

  pyroscope:
    image: grafana/pyroscope
    ports:
      - "4040:4040"

  # 1. 从源码通过 spring-boot 运行程序
  spring-boot3-monolith:
    container_name: spring-boot3-monolith
    image: maven:3.9.6-eclipse-temurin-21
    volumes:
      - .:/usr/src/workdir
      - ~/.m2:/root/.m2
    working_dir: /usr/src/workdir
    command: "mvn clean -DskipTests spring-boot:run"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD-SHELL','curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  # 2. mvn spring-boot:build-image
  # docker run  -p 8080:8080 --platform linux/amd64 --network host  spring-boot3-monolith:0.0.1-SNAPSHOT

  # 3. 使用 docker 构建镜像，需要先执行 maven package -DskipTests
  spring-boot3-monolith-image:
    build: .
    image: chensoul/spring-boot3-monolith
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD-SHELL','curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  rabbitmq_data:
  gitlab_data:
  mysql_data:
  postgres_data:
  redis_data:
  sonar_data:
  jenkins_data:
  nexus_data:
  mongo_data:
  artifactory_data:
