apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot3-monolith
  template:
    metadata:
      labels:
        app: spring-boot3-monolith
    spec:
      containers:
        - name: spring-boot3-monolith
          image: chensoul/spring-boot3-monolith:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: POSTGRES_HOST
              value: postgres-service
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
