apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot3-monolith-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: monolith.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot3-monolith-service
                port:
                  number: 8080
