apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot3-monolith-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chensoul/spring-boot3-monolith.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
